//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sequencing.WeatherApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendInfo
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> SendEmail { get; set; }
        public Nullable<bool> SendSms { get; set; }
        public string UserEmail { get; set; }
        public string UserPhone { get; set; }
        public Nullable<System.DateTime> LastSendDt { get; set; }
        public string City { get; set; }
        public string DataFileName { get; set; }
        public string DataFileId { get; set; }
        public string TimeWeekDay { get; set; }
        public string TimeWeekEnd { get; set; }
        public string TimeZoneValue { get; set; }
        public Nullable<decimal> TimeZoneOffset { get; set; }
        public Nullable<WeekEndMode> WeekendMode { get; set; }
        public Nullable<TemperatureMode> Temperature { get; set; }
        public string SmsId { get; set; }
        public Nullable<bool> SmsUseFrom2 { get; set; }
        public Nullable<bool> SendRoost { get; set; }
        public string LastWeatherUpdate { get; set; }
        public Nullable<System.DateTime> WeatherUpdateDt { get; set; }
    }
}
