//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sequencing.WeatherApp
{
    using System;
    
    public enum WeekEndMode : int
    {
        SendSms = 0,
        SendEmail = 1,
        SendBoth = 2,
        None = 3
    }
}
