# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Weather-My-Way' do

pod 'sequencing-master-plugin-api-objc', '~> 1.4.1’
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Firebase'
pod 'Firebase/Crash'

end

