//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sequencing.WeatherApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendForecast
    {
        public long UserId { get; set; }
        public long SendForecastID { get; set; }
        public long WeatherCond { get; set; }
        public long VitaminD { get; set; }
        public long MelanomaRisk { get; set; }
        public System.DateTime ForecastDate { get; set; }
        public int AppTypeId { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual MelanomaRisk MelanomaRisk1 { get; set; }
        public virtual SendInfo SendInfo { get; set; }
        public virtual VitaminD VitaminD1 { get; set; }
        public virtual ApplicationName ApplicationName { get; set; }
    }
}
